services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    container_name: travel-backend
    working_dir: /app
    environment:
      - PORT=5000
      - MONGO_URI=mongodb://mongo:27017/travel_connect
    ports:
      - "5000:5000"
    depends_on:
      - mongo

  frontend:
    build:
      context: ./travel-connect-frontend
    container_name: travel-frontend
    ports:
      - "3000:80"
    depends_on:
      - backend

  mongo:
    image: mongo:6.0
    container_name: travel-mongo
    restart: unless-stopped
    environment:
      MONGO_INITDB_DATABASE: travel_connect
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
