FROM node:18-alpine
WORKDIR /app
COPY travel-connect-backend/package.json travel-connect-backend/package-lock.json ./
RUN npm install --production
COPY travel-connect-backend/. ./
ENV PORT=5000
EXPOSE 5000
CMD ["node", "index.js"]
